// This file is automatically generated during build
export const BUILD_INFO = {
  version: '0.0.0',
  namespace: 'my-app',
  libVersion: 'unknown',
  libName: 'unknown',
  commit: 'd847dc8b250d4b0e8c23dfe66d9f779f73a61eb7',
  branch: 'main',
  lastCommitMessage: 'fix: update workflow reference for deployment configuration',
  lastCommitAuthor: 'mahindar5',
  lastCommitDate: '2025-03-30 23:42:04 -0700',
  buildNumber: '1743817123861',
  buildId: 'build-1743817123861',
  buildUrl: '',
  buildEnvironment: 'development',
  buildHost: 'DESKTOP-NUHLUK',
  buildTarget: 'development',
  nodeVersion: 'v22.13.1',
  npmVersion: '10.9.2',
  os: 'win32',
  arch: 'x64',
  timestamp: '2025-04-05T01:38:43.835Z',
  buildDate: '2025-04-04',
  buildTime: '6:38:43 p.m.',
  dependencies: {
    angular: '19.1.0',
    typescript: '~5.7.2',
    rxjs: '~7.8.0',
    materialUI: 'unknown'
  }
};
